# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build PDF & ePub
formats:
    - epub
    - pdf

python:
  # Keep version in sync with tox.ini (docs).
  version: 3.8
  install:
    - requirements: constraints_dev.txt

build:
  image: latest
