site_name: LLM Ingestion Pipeline
theme:
  name: material

# Use the Awesome Pages plugin for better navigation structure
nav:
  - Home: index.md
  - About: about.md
  - Prompts: prompts/index.md
  - API Reference: reference/ 
  - Features:
      - CI/CD with Github Actions: features/cicd.md
      - Linting & code quality: features/linting.md
      - Makefile: features/makefile.md
      - Dependency management with Poetry: features/poetry.md
      - Publishing to PyPI or Artifactory: features/publishing.md
      - Testing with Pytest: features/pytest.md
      - Test coverage with codecov: features/codecov.md
      - Documentation with MkDocs: features/mkdocs.md
      - Compatibility testing with Tox: features/tox.md
      - Containerization with Docker: features/docker.md
      - Devcontainer with VSCode: features/devcontainer.md
  - Tutorial: tutorial.md
  - Prompt Arguments: prompt_arguments.md  
plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
        - gen_pages.py
  - llm_plugin:
      module_name: plugins.llm_plugin
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:   
            docstring_style: google
            show_source: true
            show_signature: true
  - awesome-pages:
      # Collapse single pages in the navigation
      collapse_single_pages: true 
       # Other options:
      - sort_pages: true  # Sort pages alphabetically
      - sort_nav: true   # Sort navigation items alphabetically
      - remove_empty_folders: true
  - material-extensions:
      # Add a highlight.js extension for code highlighting
      - highlighter
      - admonition
      - anchor     # For generating anchors for headings
      - attribute_lists  # For attribute lists in tables
      - def_list   # For definition lists
      - footnotes  # For footnotes
      - md_in_html # For embedding Markdown in HTML
      - meta       # For metadata in pages
      - sane_list
      - toc:
          permalink: true
      - pymdownx.arithmatex:
          generic: true  
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
   
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github        
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fpgmaas/cookiecutter-poetry
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cookiecutter-poetry/
